# vim: set ts=2 sts=2 sw=2 et ci ft=yaml:
fretboard:
  drawing:
      background_color:
      font_color: dimgray
      font_family: Verdana
      font_size: 24
      height: 400
      width: 300
      spacing: 30
      label_all_frets: false
  nut:
      color: darkslategray
      size: 10
  fret:
      color: darkgray
      size: 2
  inlays:
      color: darkslategray
      radius: 2
  string:
      color: darkslategray
      size: 3
      muted_font_color:
      open_font_color:
      label_font_family:
      label_font_size:
      equal_weight: false

  marker:
      border_color: black
      color: darkslategray
      font_color: white
      radius: 18
      stroke_width: 2
  title:
      font_color: dimgray
      font_family: Verdana
      font_size: 30
  fret_label:
      width: 28
      font_style: italic


chord:
  string:
    muted_font_color: silver
    open_font_color: darkslategray
